repos:
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.144.0 # Use a specific version tag
    hooks:
      - id: semgrep
        name: Lightweight SAST Scan
        files: \.(py|js|ts|go)$ # Define file extensions to scan
        args: [
          '--config', 
          'auto'
        #  'p/flask' ,
        #  '--config', 
        #  'p/owasp-top-ten' ,
        ]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0 # Use a specific version tag
    hooks:
      - id: gitleaks
        # Only check the files being committed
        name: Check for Hardcoded Secrets