name: Comprehensive DevSecOps Pipeline (SAST, SCA, DAST)

permissions:
  # This permission is required when uploading sarifs to any repository at GitHub
  security-events: write

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: "*"

jobs:
  sast:
    name: semgrep-SAST
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Run Semgrep SAST Scan (Code Analysis)
        run : semgrep ci --config auto --sarif > semgrep.sarif   
      
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
        if: always()   
#  secret-leak:
  secret_example:
    name: secret-example
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.API_KEY }}
      run: |
        echo "✅ GOOD WAY (never printed) -->"
        echo $SUPER_SECRET > super-secret.txt
        echo "⛔ BAD WAY (Fixed by SECRET MASKING) -->"
        echo $SUPER_SECRET | tee super-secret2.txt
